#!/bin/bash
set -e

# parse arguments
POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    --docker-image)
    DOCKER_IMAGE="$2"
    shift # past argument
    shift # past value
    ;;
    --base-model-name)
    BASE_MODEL_NAME="$2"
    shift # past argument
    shift # past value
    ;;
    --weights-file1)
    WEIGHTS_FILE1="$2"
    shift # past argument
    shift # past value
    ;;
    --weights-file2)
    WEIGHTS_FILE2="$2"
    shift # past argument
    shift # past value
    ;;
    --image-source)
    IMAGE_SOURCE="$2"
    shift # past argument
    ;;
    *)    # unknown option
    POSITIONAL+=("$1") # save it in an array for later
    shift # past argument
    ;;
esac
done


BASENAME_IS=`basename $IMAGE_SOURCE`

# run predictions
DOCKER_RUN="docker run
  --entrypoint entrypoints/entrypoint.predict_both.cpu.sh \
  -v "$IMAGE_SOURCE":/src/$BASENAME_IS
  -v "$WEIGHTS_FILE1":/src/weights1.hdf5
  -v "$WEIGHTS_FILE2":/src/weights2.hdf5
  $DOCKER_IMAGE $BASE_MODEL_NAME /src/weights1.hdf5 /src/weights2.hdf5 /src/$BASENAME_IS"

eval $DOCKER_RUN
